global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.Identity.Web;
global using LitExplore.Server;
global using Microsoft.Identity.Web.Resource;
global using LitExplore.ApplicationLogic;
global using LitExplore.Storage;
